# Generated by Django 4.1.4 on 2023-01-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nationalCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('type_of_employment', models.CharField(choices=[('RG', 'رسمی قطعی'), ('RA', 'رسمی آزمایشی'), ('PE', 'پیمانی'), ('GM', 'قرارداد کارمعین'), ('GK', 'قرارداد کارگری'), ('SH', 'شرکتی')], max_length=2)),
                ('employment_status', models.CharField(choices=[('SH', 'شاغل'), ('MO', 'مرخصی'), ('MA', 'مامور از'), ('MB', 'مامور به'), ('BA', 'بازنشسته')], default='SH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('nationalCode', models.CharField(max_length=2)),
                ('date_of_birth', models.DateField()),
                ('sex', models.BooleanField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childs.employee')),
            ],
        ),
    ]
