# Generated by Django 4.1.4 on 2023-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='nationalCode',
            field=models.CharField(max_length=10),
        ),
    ]
