# Generated by Django 4.1.4 on 2022-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='directPhone',
            field=models.CharField(blank=True, max_length=8, verbose_name='مستقیم'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='پست الکترونیک'),
        ),
        migrations.AlterField(
            model_name='person',
            name='internalPhone',
            field=models.CharField(blank=True, max_length=3, verbose_name='داخلی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=11, verbose_name='همراه'),
        ),
    ]
